In [6]:
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(10, 24)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [4]:
np.arange(10, 24, 2)

array([10, 12, 14, 16, 18, 20, 22])

In [8]:
# reshape разбивает одномерный массив в двухмерный
np.arange(20).reshape([2, 10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [9]:
np.random.seed(0)
np.random.randint(50, 80, (4, 3, 3))

array([[[62, 65, 71],
        [50, 53, 77],
        [53, 57, 59]],

       [[69, 71, 68],
        [54, 73, 56],
        [74, 74, 62]],

       [[76, 51, 56],
        [57, 73, 64],
        [74, 67, 55]],

       [[75, 63, 58],
        [59, 70, 69],
        [66, 69, 55]]])

In [11]:
np.random.seed(0)
np.random.randint(50, 80, (4, 3, 3)).flatten()

array([62, 65, 71, 50, 53, 77, 53, 57, 59, 69, 71, 68, 54, 73, 56, 74, 74,
       62, 76, 51, 56, 57, 73, 64, 74, 67, 55, 75, 63, 58, 59, 70, 69, 66,
       69, 55])