In [1]:
import numpy as np

# 1.Калькуляция в массивах

In [2]:
prices = np.array([19.99, 29.99, 14.99, 23.99, 9.99])

In [3]:
quantites = np.array([10, 5, 8, 12, 3])

## a. Умножение в массивах

In [5]:
revenue_per_product = prices * quantites
revenue_per_product

array([199.9 , 149.95, 119.92, 287.88,  29.97])

## b. Подсчет суммы массива

In [7]:
total_revenue = np.sum(revenue_per_product)
total_revenue

787.62

# 2. Анализ статистики блога

In [8]:
views = np.array([1000, 300, 800, 200, 500])
views

array([1000,  300,  800,  200,  500])

## a. Максисальное значение

In [11]:
max_views = np.max(views)
max_views

1000

## b. Минимальное значение

In [12]:
min_views = np.min(views)
min_views

200

# 3.Разделение заказа на партии

In [13]:
order_ids = np.array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009]) 
order_ids

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009])

In [14]:
batches = np.split(order_ids, 3)
batches

[array([1001, 1002, 1003]),
 array([1004, 1005, 1006]),
 array([1007, 1008, 1009])]

# 4.Категоризация

In [19]:
ratings = np.array([4.5, 4.2, 3.7, 2.8, 4.9, 3.3, 4.4, 2.1, 1.9])
ratings

array([4.5, 4.2, 3.7, 2.8, 4.9, 3.3, 4.4, 2.1, 1.9])

In [20]:
positive_ratings = ratings[ratings >=4.0]
positive_ratings

array([4.5, 4.2, 4.9, 4.4])

In [21]:
negative_ratings = ratings[ratings < 4.0]
negative_ratings

array([3.7, 2.8, 3.3, 2.1, 1.9])

# 5.Калькуляция в двумерных массивах

In [24]:
order_quantities = np.array([[5, 3, 2, 7],[10, 6, 3, 9]])
order_quantities

array([[ 5,  3,  2,  7],
       [10,  6,  3,  9]])

In [26]:
# Сложение по нулевой оси то есть вертикально
total_quantities_sold = np.sum(order_quantities, axis=0)
total_quantities_sold

array([15,  9,  5, 16])

In [27]:

total_quantities_per_order = np.sum(order_quantities, axis=1)
total_quantities_per_order

array([17, 28])

In [28]:
average_quantities_sold = np.mean(order_quantities, axis=0)
average_quantities_sold

array([7.5, 4.5, 2.5, 8. ])

# 6. Средний рейтинг товара и максимальный рейтинг Категории (Двумерный массив)

In [12]:
product_rating = np.array([
    [4.5, 5.1, 2.5, 3.8],
    [2.9, 4.8, 4.7, 3.2],
    [2.0, 3.9, 0.5, 4.9]
])
print(np.shape(product_rating))
product_rating

(3, 4)


array([[4.5, 5.1, 2.5, 3.8],
       [2.9, 4.8, 4.7, 3.2],
       [2. , 3.9, 0.5, 4.9]])

In [13]:
average_rating_per_category = np.mean(product_rating, axis=1)
average_rating_per_category

array([3.975, 3.9  , 2.825])

In [14]:
average_rating_per_category = np.mean(product_rating, axis=0)
average_rating_per_category

array([3.13333333, 4.6       , 2.56666667, 3.96666667])

In [15]:
average_rating_per_category = np.max(product_rating, axis=0)
average_rating_per_category

array([4.5, 5.1, 4.7, 4.9])

# 7. Калькуляция и генерация в трехмерном массиве

In [16]:
companies = ['Google', 'Microsoft', 'Apple']
days = ['Mon 1 April', 'Tue 2 April'] 
price_types = ['Open', 'Close', 'High', 'Low']

In [23]:
np.random.seed(1)
stock_prices = np.round(np.random.random((len(companies), len(days), len(price_types))), 3)
stock_prices

array([[[0.417, 0.72 , 0.   , 0.302],
        [0.147, 0.092, 0.186, 0.346]],

       [[0.397, 0.539, 0.419, 0.685],
        [0.204, 0.878, 0.027, 0.67 ]],

       [[0.417, 0.559, 0.14 , 0.198],
        [0.801, 0.968, 0.313, 0.692]]])

In [24]:
stock_prices.shape

(3, 2, 4)

In [31]:
for index_axis_0, company in enumerate(companies):
    print(f'Stock prices for the {company}: ')
    for index_axis_1, day in enumerate(days):
        print(f'Day: {day} ')
        for index_axis_2, price_type in enumerate(price_types):
            print(f' {price_type} Price: {stock_prices[index_axis_0,index_axis_1,index_axis_2]} ')
        print('')
    print('')

Stock prices for the Google: 
Day: Mon 1 April 
 Open Price: 0.417 
 Close Price: 0.72 
 High Price: 0.0 
 Low Price: 0.302 

Day: Tue 2 April 
 Open Price: 0.147 
 Close Price: 0.092 
 High Price: 0.186 
 Low Price: 0.346 


Stock prices for the Microsoft: 
Day: Mon 1 April 
 Open Price: 0.397 
 Close Price: 0.539 
 High Price: 0.419 
 Low Price: 0.685 

Day: Tue 2 April 
 Open Price: 0.204 
 Close Price: 0.878 
 High Price: 0.027 
 Low Price: 0.67 


Stock prices for the Apple: 
Day: Mon 1 April 
 Open Price: 0.417 
 Close Price: 0.559 
 High Price: 0.14 
 Low Price: 0.198 

Day: Tue 2 April 
 Open Price: 0.801 
 Close Price: 0.968 
 High Price: 0.313 
 Low Price: 0.692 


