In [2]:
import numpy as np

In [3]:
np.zeros((3, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [4]:
np.random.seed(0)
np.random.random(size=(2, 4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ]])

In [11]:
np.random.seed(0)
np.random.randint(10, 20, size=(2,4))

array([[15, 10, 13, 13],
       [17, 19, 13, 15]])

In [13]:
np.random.seed(0)
np.random.choice([1, 2, 3], size=15)

array([1, 2, 1, 2, 2, 3, 1, 3, 1, 1, 1, 3, 2, 3, 3])